set names utf8mb4;
-- ygb_phase49_bulk_simulation_seed_cleanup.sql
-- 重复导入 phase49 前执行；仅删除 sim_seed 批次数据

delete from sys_logininfor where info_id between 972001 and 972050;
delete from sys_oper_log where oper_id between 971501 and 971550;
delete from sys_notice where create_by = 'sim_seed';
delete from ygb_worker_realname_apply where create_by = 'sim_seed';
delete from ygb_worker_push_test_record where create_by = 'sim_seed';
delete from ygb_worker_notice_message where create_by = 'sim_seed';
delete from ygb_worker_upload_record where create_by = 'sim_seed';
delete from ygb_worker_point_exchange where create_by = 'sim_seed';
delete from ygb_worker_point_ledger where create_by = 'sim_seed';
delete from ygb_worker_point_goods where create_by = 'sim_seed';
delete from ygb_worker_setting where create_by = 'sim_seed';
delete from ygb_worker_video_progress where progress_id between 957001 and 957050;
delete from ygb_worker_activity_join where create_by = 'sim_seed';
delete from ygb_worker_feedback where create_by = 'sim_seed';
delete from ygb_worker_resume where create_by = 'sim_seed';
delete from ygb_worker_legal_consult where create_by = 'sim_seed';
delete from ygb_worker_complaint where create_by = 'sim_seed';
delete from ygb_worker_job_apply where create_by = 'sim_seed';
delete from ygb_worker_job_post where create_by = 'sim_seed';
delete from ygb_portal_content where create_by = 'sim_seed';
delete from ygb_module_record where create_by = 'sim_seed';
delete from t_height_work_report_worker where row_id between 103001 and 103080;
delete from t_height_work_report where create_by = 'sim_seed';
delete from t_salary_arrears_handle where create_by = 'sim_seed';
delete from t_contract_template where create_by = 'sim_seed' and template_code like 'TPL-SIM-%';
delete from t_cockpit_config where create_by = 'sim_seed' and config_code like 'cockpit-sim-%';
delete from t_ai_report_subscription where create_by = 'sim_seed';
delete from t_ai_report_task where create_by = 'sim_seed';
delete from t_ai_report_item where item_id between 922001 and 922080;
delete from t_ai_report where create_by = 'sim_seed';
delete from t_ai_report_config where create_by = 'sim_seed';
delete from t_stat_report_item where item_id between 911001 and 911080;
delete from t_stat_report where create_by = 'sim_seed';
delete from t_cockpit_map_feature where create_by = 'sim_seed';
delete from t_cockpit_snapshot where create_by = 'sim_seed';
delete from t_occupation_monitor where create_by = 'sim_seed';
delete from t_newform_worker where create_by = 'sim_seed';
delete from t_credit_score where create_by = 'sim_seed';
delete from t_prevention_fund where create_by = 'sim_seed';
delete from t_aq_insurance where create_by = 'sim_seed';
delete from t_warning_handle_log where create_by = 'sim_seed';
delete from t_warning where create_by = 'sim_seed';
delete from t_warning_rule where create_by = 'sim_seed';
delete from t_prevention_project where create_by = 'sim_seed';
delete from t_injury_event where create_by = 'sim_seed';
delete from t_device_event where create_by = 'sim_seed';
delete from t_device_command_log where create_by = 'sim_seed';
delete from t_device where create_by = 'sim_seed';
delete from t_fake_outsourcing_record where create_by = 'sim_seed';
delete from t_employment_proportion where create_by = 'sim_seed';
delete from t_uninsured_list where create_by = 'sim_seed';
delete from t_tax_compare where create_by = 'sim_seed';
delete from t_social_base_compare where create_by = 'sim_seed';
delete from t_social_payment where create_by = 'sim_seed';
delete from t_salary_detail where create_by = 'sim_seed';
delete from t_salary_batch where create_by = 'sim_seed';
delete from t_attendance_monthly where create_by = 'sim_seed';
delete from t_attendance_raw where create_by = 'sim_seed';
delete from t_labor_contract where create_by = 'sim_seed';
delete from t_person where create_by = 'sim_seed';
delete from t_enterprise where create_by = 'sim_seed';