create table if not exists ygb_worker_push_test_record (
  record_id bigint(20) not null auto_increment,
  user_id bigint(20) not null,
  person_id bigint(20) default null,
  person_name varchar(64) default '',
  trace_id varchar(64) default '',
  push_client_id_masked varchar(128) default '',
  push_platform varchar(32) default '',
  notification_permission varchar(32) default '',
  notify_enabled char(1) default '1',
  gateway_provider varchar(64) default '',
  gateway_url varchar(255) default '',
  target_path varchar(255) default '',
  target_query_text text,
  action_label varchar(64) default '',
  source_label varchar(64) default '',
  request_body text,
  response_body text,
  test_status varchar(16) default '',
  status_message varchar(500) default '',
  create_by varchar(64) default '',
  create_time datetime default sysdate(),
  update_by varchar(64) default '',
  update_time datetime default null,
  remark varchar(500) default '',
  del_flag char(1) default '0',
  primary key (record_id),
  key idx_worker_push_test_user (user_id),
  key idx_worker_push_test_trace (trace_id),
  key idx_worker_push_test_status (test_status)
) engine=innodb default charset=utf8mb4 comment='劳动者端推送测试记录';
